# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75fb17d416caa477c3710e8c77f2d348f50b16f7acf07b8c2451e8e11a85be97a5bcd5c521cb66b3c44f8df0527a967014b54db1859f6bdf5b2bb280569afc30

test:
  secret_key_base: 232a9658c6075cff23c5d5e561cd8512fbc89ed1154afeee792316c1aa4d076b16f845bfc7436345f5dc6ade39358ff3ba4751b88b7c5b41996482852f985b45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
